### ISSUE TITLE
Script crashes when trying to swipe the screen to look around for enemies

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/azurlane-auto#3]
#### Environment details

* azurlane-auto version (version on first line of `CHANGELOG.md`): 0.1.0

#### Issue variability
Consistent

#### Issue
Script crashes when trying to swipe the screen to look around for enemies

#### Log
```
Traceback (most recent call last):
  File "azurlane-auto.py", line 97, in <module>
    script.run_combat_cycle()
  File "azurlane-auto.py", line 41, in run_combat_cycle
    if self.modules['combat'].combat_logic_wrapper():
  File "D:\azurlane-auto\modules\combat.py", line 69, in combat_logic_wrapper
    if self.clear_trash():
  File "D:\azurlane-auto\modules\combat.py", line 252, in clear_trash
    enemy_coord = self.get_closest_enemy()
  File "D:\azurlane-auto\modules\combat.py", line 161, in get_closest_enemy
    Util.swipe(640, 360 - y_dist * multiplier,
NameError: name 'Util' is not defined
```

**Comment by perryhuynh** [comment]
Resolved via 4695f89
