### ISSUE TITLE
Crash when starting script

### ISSUE THREAD

**Issue by perryhuynh** [perryhuynh/azurlane-auto#4]
* azurlane-auto version (version on first line of `CHANGELOG.md`): 0.1.1

#### Issue variability
Consistent

#### Issue
Script crashes upon starting

#### Log
```
Traceback (most recent call last):
  File "azurlane-auto.py", line 98, in <module>
    script.run_mission_cycle()
  File "azurlane-auto.py", line 54, in run_mission_cycle
    if self.modules['mission']:
KeyError: 'mission'
```

**Comment by perryhuynh** [comment]
Closed via 5cfd4d7
