### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by LazyBoii** [perryhuynh/azurlane-auto#9]
#### Environment details

0.1.1

#### Issue variability

Persistent

#### Issue

![image](https://user-images.githubusercontent.com/46345793/50664050-cc074a00-0f79-11e9-92a4-a68d1803c47b.png)

#### Log
```
[94m[2019-01-03 17:02:22] Initializing config module[0m
[94m[2019-01-03 17:02:22] Validating config[0m
[94m[2019-01-03 17:02:22] Starting azurlane-auto![0m
error: protocol fault (couldn't read status): Connection reset by peer
[94m[2019-01-03 17:02:23] Navigating to map.[0m
* daemon not running; starting now at tcp:5037
* daemon started successfully
Traceback (most recent call last):
  File "azurlane-auto.py", line 96, in <module>
    script.run_combat_cycle()
  File "azurlane-auto.py", line 41, in run_combat_cycle
    if self.modules['combat'].combat_logic_wrapper():
  File "C:\Users\Darryl\Downloads\Azur Lane\azurlane-auto-master\modules\combat.py", line 57, in combat_logic_wrapper
    Utils.wait_and_touch('map_{}'.format(self.sortie_map), 5, 0.85)
  File "C:\Users\Darryl\Downloads\Azur Lane\azurlane-auto-master\util\utils.py", line 196, in wait_and_touch
    if cls.find_and_touch(image, similarity):
  File "C:\Users\Darryl\Downloads\Azur Lane\azurlane-auto-master\util\utils.py", line 173, in find_and_touch
    region = cls.find(image, similarity)
  File "C:\Users\Darryl\Downloads\Azur Lane\azurlane-auto-master\util\utils.py", line 94, in find
    width, height = template.shape[::-1]
AttributeError: 'NoneType' object has no attribute 'shape'
```

#### Config
```
[Commissions]
Enabled: False

[Combat]
Enabled: True
Map: 1-1
KillsNeeded: 1
Hard: False
Formation:
AltClearFleet: False
BossFleet: False

[Missions]
Enabled: False
```

**Comment by perryhuynh** [comment]
Sorry this is because there isn't an asset for 1-1 yet, been really busy IRL so hopefully in the next week I will update it to have assets for every single map as well as implement the page navigation. The only ones I that are on the repository are 6-1 and 6-2. 

Also for now I would use this branch: https://github.com/perryhuynh/azurlane-auto/tree/feature/7-combat-fixes

**Comment by LazyBoii** [comment]
oh alright thanks 6-1 and 6-2 are fine for now; take your time.

**Comment by perryhuynh** [comment]
the map currently also has to be already on the screen when you click on the attack button until I implement the page navigation

**Comment by LazyBoii** [comment]
ya i figured that already set it up and its running smooth so far, thanks for the hard work ^^
